gia-api/apps/api/v1/urls.py
from decorator_include import decorator_include
from django.urls import include, path
from django.views.decorators.cache import never_cache
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r"date", views.DateViewSet)
router.register(r"level", views.LevelViewSet)
router.register(r"organisation", views.OrganisationViewSet)
router.register(r"position", views.PositionViewSet)
router.register(r"employee", views.EmployeeViewSet, basename="employee")
router.register(r"place", views.PlaceViewSet)
router.register(r"exam", views.ExamViewSet)
router.register(r"examflat", views.ExamFlatViewSet, basename="flat")
router.register(r"examfull", views.ExamFullViewSet, basename="full")
router.register(r"datasource", views.DataSourceViewSet)
router.register(r"datafile", views.DataFileViewSet)
router.register(r"subscription", views.SubscriptionViewSet, basename="subscription")

urlpatterns = [
    path("api-auth/", include("rest_framework.urls")),
    path("auth/", decorator_include(never_cache, "dj_rest_auth.urls")),
    path("auth/registration/", include("dj_rest_auth.registration.urls")),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "swagger/",
        SpectacularSwaggerView.as_view(url_name="apiv1:schema"),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        SpectacularRedocView.as_view(url_name="apiv1:schema"),
        name="schema-redoc",
    ),
]

urlpatterns += router.urls

gia-api/apps/rcoi/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views
from .sitemap import index, sitemap, sitemaps_context

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path(
        "robots.txt",
        cache_page(86400)(
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        name="robotstxt",
    ),
    path(
        "sitemap.xml",
        cache_page(86400)(index),
        {"sitemaps": sitemaps_context, "sitemap_url_name": "rcoi:sitemap_section"},
        name="sitemap",
    ),
    path(
        "sitemap-<section>.xml",
        cache_page(86400)(sitemap),
        {"sitemaps": sitemaps_context},
        name="sitemap_section",
    ),
    path("admin/update_db/", views.update_db_view, name="update_db"),
    path("admin/clear_caches/", views.clear_caches_view, name="clear_caches"),
    # urls for Date
    path("date/", views.DateListView.as_view(), name="date_list"),
    path(
        "date/detail/<int:pk>/",
        views.DateDetailView.as_view(),
        name="date_detail",
    ),
    # urls for Level
    path("level/", views.LevelListView.as_view(), name="level_list"),
    path(
        "level/detail/<int:pk>/",
        views.LevelDetailView.as_view(),
        name="level_detail",
    ),
    # urls for Organisation
    path(
        "organisation/",
        views.OrganisationTableView.as_view(),
        name="organisation",
    ),
    path(
        "organisation/detail/<int:pk>/",
        views.OrganisationDetailView.as_view(),
        name="organisation_detail",
    ),
    # urls for Position
    path("position/", views.PositionListView.as_view(), name="position_list"),
    path(
        "position/detail/<int:pk>/",
        views.PositionDetailView.as_view(),
        name="position_detail",
    ),
    # urls for Employee
    path("employee/", views.EmployeeTableView.as_view(), name="employee"),
    path(
        "employee/detail/<int:pk>/",
        views.EmployeeDetailView.as_view(),
        name="employee_detail",
    ),
    # urls for Place
    path("place/", views.PlaceTableView.as_view(), name="place"),
    path(
        "place/detail/<int:pk>/",
        views.PlaceDetailView.as_view(),
        name="place_detail",
    ),
    # urls for Exam
    path("exam/", views.ExamTableView.as_view(), name="exam"),
    path(
        "exam/detail/<int:pk>/",
        views.ExamDetailView.as_view(),
        name="exam_detail",
    ),
]

gia-api/config/urls.py
from decorator_include import decorator_include
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView

urlpatterns = [
    path("", decorator_include(never_cache, "django_prometheus.urls")),
    path("", include(("apps.rcoi.urls", "apps.rcoi"), namespace="rcoi")),
    path("api/v1/", include(("apps.api.v1.urls", "apps.api.v1"), namespace="apiv1")),
    path(settings.ADMIN_URL, admin.site.urls),
    # This urls used in mail templates
    re_path(
        r"^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$",
        TemplateView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^registration/confirm-email/(?P<key>[-:\w]+)/$",
        TemplateView.as_view(),
        name="account_confirm_email",
    ),
]

if settings.DEBUG:  # pragma: no cover
    from django.views import defaults

    urlpatterns += [
        path(
            "400/",
            defaults.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            defaults.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            defaults.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", defaults.server_error),
    ]

    if settings.DEBUG_TOOLBAR:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            path("__reload__/", include("django_browser_reload.urls")),
            *urlpatterns,
        ]

gia-api/apps/rcoi/views.py
import contextlib
import sys

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.sites.requests import RequestSite
from django.db.models import Count
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic import DetailView, ListView, TemplateView
from django_tables2 import RequestConfig

from .filters import (
    EmployeeFilter,
    ExamFilter,
    OrganisationFilter,
    PlaceFilter,
    PlaceWithExamsFilter,
)
from .models import (
    DataFile,
    DataSource,
    Date,
    Employee,
    Exam,
    Level,
    Organisation,
    Place,
    Position,
    RcoiUpdater,
)
from .tables import (
    EmployeeTable,
    ExamTable,
    OrganisationTable,
    PlaceTable,
    PlaceWithExamsTable,
)


class TemplateViewWithContext(TemplateView):
    """Base template view that provides additional context data for templates."""

    model = None
    template_name = None

    def get_context_data(self, **kwargs):
        """Get the context data for the template, including data sources, last update, and link relation."""
        context = super().get_context_data(**kwargs)
        context["sources"] = DataSource.objects.all()
        try:
            context["updated"] = DataFile.objects.latest("modified").modified
        except DataFile.DoesNotExist:
            context["updated"] = ""
        context["link_rel"] = (
            f"{self.request.scheme}://{RequestSite(self.request).domain}{self.request.path}"
        )
        return context


class HomeView(TemplateViewWithContext):
    """Home page view."""

    template_name = "rcoi/home.html"


class FilteredSingleTableView(TemplateViewWithContext):
    """Base view for table with filtered data."""

    table_class = None
    paginate_by = 50
    filter_class = None

    def get_queryset(self, **kwargs):
        return self.model.objects.select_related()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filter_ = self.filter_class(
            data=self.request.GET,
            request=self.request,
            queryset=self.get_queryset(**kwargs),
        )
        filter_.form.helper = self.filter_class().helper
        table = self.table_class(filter_.qs)
        RequestConfig(self.request, paginate={"per_page": self.paginate_by}).configure(
            table,
        )
        context["filter"] = filter_
        context["table"] = table
        with contextlib.suppress(MultiValueDictKeyError):
            context["table_sort"] = self.request.GET["sort"]

        return context


class EmployeeTableView(FilteredSingleTableView):
    """Table view for employees."""

    model = Employee
    table_class = EmployeeTable
    filter_class = EmployeeFilter
    template_name = "rcoi/employee.html"


class OrganisationTableView(FilteredSingleTableView):
    """Table view for organisations."""

    model = Organisation
    table_class = OrganisationTable
    filter_class = OrganisationFilter
    template_name = "rcoi/organisation.html"


class PlaceTableView(FilteredSingleTableView):
    """Table view for places."""

    model = Place
    table_class = PlaceTable
    filter_class = PlaceFilter
    template_name = "rcoi/place.html"


class ExamTableView(FilteredSingleTableView):
    """Table view for exams."""

    model = Exam
    table_class = ExamTable
    filter_class = ExamFilter
    template_name = "rcoi/exam.html"


class DetailViewWithContext(DetailView):
    """Base detail view that provides additional context data for templates."""

    model = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sources"] = DataSource.objects.all()
        try:
            context["updated"] = DataFile.objects.latest("modified").modified
        except DataFile.DoesNotExist:
            context["updated"] = ""
        context["link_rel"] = (
            f"{self.request.scheme}://{RequestSite(self.request).domain}{self.request.path}"
        )
        return context


class OrganisationDetailView(DetailViewWithContext):
    """Detail view for organisation."""

    model = Organisation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["employees"] = (
            self.object.employees.annotate(num_exams=Count("exams"))
            .prefetch_related(
                "exams__date",
                "exams__level",
                "exams__place",
                "exams__position",
            )
            .order_by("name")
        )
        context["dates"] = (
            Date.objects.filter(
                id__in=[
                    exam.date_id
                    for employee in context["employees"]
                    for exam in employee.exams.all()
                ],
            )
            .distinct()
            .order_by("-date")
        )
        return context


class EmployeeDetailView(DetailViewWithContext):
    """Detail view for employee."""

    model = Employee

    def get_queryset(self):
        return super().get_queryset().select_related()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["exams"] = self.object.exams.select_related()
        return context


class PlaceDetailView(FilteredSingleTableView):
    """Detail view for place."""

    model = Exam
    table_class = PlaceWithExamsTable
    filter_class = PlaceWithExamsFilter
    template_name = "rcoi/place_detail.html"

    def get_queryset(self, **kwargs):
        return self.model.objects.filter(place=self.kwargs.get("pk")).select_related()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["place"] = Place.objects.filter(pk=self.kwargs.get("pk")).get()
        return context

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Place.DoesNotExist:
            raise Http404 from None


class DateListView(ListView):
    """List view for dates."""

    model = Date


class DateDetailView(DetailView):
    """Detail view for a date."""

    model = Date


class LevelListView(ListView):
    """List view for levels."""

    model = Level


class LevelDetailView(DetailView):
    """Detail view for a level."""

    model = Level


class PositionListView(ListView):
    """List view for positions."""

    model = Position


class PositionDetailView(DetailView):
    """Detail view for a position."""

    model = Position


class ExamDetailView(DetailView):
    """Detail view for an exam."""

    model = Exam


@staff_member_required
def update_db_view(request):
    """Update database."""
    if request.method == "POST":
        # noinspection PyBroadException
        try:
            updated = RcoiUpdater().run()
            if updated:
                messages.info(request, "База данных обновлена!")
            else:
                messages.info(request, "Изменений нет!")
        except Exception:  # noqa: BLE001
            messages.error(request, sys.exc_info())
    return redirect(reverse("admin:index"))


@staff_member_required
def clear_caches_view(request):
    """Clear all caches."""
    if request.method == "POST":
        # noinspection PyBroadException
        try:
            from django.core.cache import cache

            res = cache.clear()
            messages.info(request, f"Кэш очищен! Удалено ключей: {res}")
        except Exception:  # noqa: BLE001
            messages.error(request, sys.exc_info())
    return redirect(reverse("admin:index"))

gia-api/apps/templates/rcoi/button_mobile.html
<div class="visible-xs-block">
        <a href="https://gia.devmem.ru" role="button" class="btn btn-lg btn-success btn-block">
            <strong>Открыть версию для мобильных</strong>
        </a>
    <div class="bottom-buffer"><hr/></div>
</div>

gia-api/apps/templates/rcoi/date_detail.html
{% extends "base.html" %}
{% block content %}
    <p><a class="btn btn-default" href="{% url 'rcoi:date_list' %}">ExamDate Listing</a></p>
    <table class="table">
        <tr>
            <td>date</td>
            <td>{{ object.date }}</td>
        </tr>
    </table>
{% endblock %}

gia-api/apps/templates/rcoi/date_list.html
{% extends "base.html" %}
{% block content %}
    <p><a class="btn btn-default" href="{% url 'rcoi:date_list' %}">ExamDate Listing</a></p>
    <table class="table">
        <tr>
            <td>ID</td>
            <td>Link</td>
            <td>date</td>
        </tr>
        {% for object in object_list %}
            <tr>
                <td>{{ object.id }}</td>
                <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
                <td>{{ object.date }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

gia-api/apps/templates/rcoi/disclaimer.html
<div class="panel panel-warning">
    <div class="panel-heading">
        Отказ от ответственности
    </div>
    <div class="panel-body">
        Сайт gia-api.devmem.ru не связан с РЦОИ города Москвы
        и разработан частным лицом,
        заинтересованным в удобном представлении информации.
        Данные получены в автоматическом режиме
        из общедоступных файлов эксель, размещенных на
        <a href="http://rcoi.mcko.ru/organizers/schedule/ege/">
            официальном сайте РЦОИ в разделе Организаторам > Планирование
        </a>.
        Сайт носит справочный характер и не может являться
        основным источником информации о распределении работников на ППЭ.
        Автор не несет ответственности за неявку организаторов на ППЭ.
        Автор не несет ответственности за достоверность,
        полноту и качество представленной информации.
    </div>
</div>

gia-api/apps/templates/rcoi/employee.html
{% extends 'rcoi/exam.html' %}
{% block description %}Список работников образовательных организаций, задействованных в работе ППЭ: организаторы аудитории, технические специалисты, руководители ППЭ, члены ГЭК на ЕГЭ и ОГЭ{% endblock %}
{% block title %}Сотрудники, участвующие в ГИА | Организаторы, технические специалисты, руководители ППЭ, члены ГЭК на ЕГЭ и ОГЭ{% endblock %}
{% block page_header %}
    <h1>Список работников, задействованных в работе ППЭ</h1>
{% endblock %}

gia-api/apps/templates/rcoi/employee_detail.html
{% extends "base.html" %}
{% block description %}График работы (расписание экзаменов) для работника ППЭ {{ object.name }}, {{ object.org.name }}.{% endblock %}
{% block title %}{{ object.name }}, {{ object.org.name }}, работник ППЭ{% endblock %}
{% block page_header %}
    <h1>{{ object.name }}<br/>
        <small><a href="{{ object.org.get_absolute_url }}">{{ object.org.name }}</a></small>
    </h1>
{% endblock %}
{% block content %}
    <div class="row bottom-buffer">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <a href="https://gia.devmem.ru/registration" role="button" class="btn btn-primary btn-block">
                Подписаться на обновления
            </a>
        </div>
        <div class="col-sm-4"></div>
    </div>
    <div class="row" id="row-main">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <table class="table table-condensed table-hover no-more-tables">
                <thead>
                <tr>
                    <th></th>
                    <th>Дата</th>
                    <th>Код ППЭ</th>
                    <th>Наименование ППЭ</th>
                    <th>Адрес ППЭ</th>
                    <th>Должность в ППЭ</th>
                </tr>
                </thead>
                <tbody>
                {% for exam in exams %}
                    {% now "Y-m-d" as todays_date %}
                    <tr{% if todays_date > exam.date.date|date:"Y-m-d" %} class="text-muted"{% endif %}>
                        <td>{% if todays_date > exam.date.date|date:"Y-m-d" %}&#10004;{% endif %}</td>
                        <td data-title="Дата">
                            <a
                                href="{{ exam.datafile.url }}"
                                rel="noopener noreferrer"
                                title="Скачать таблицу с официального сайта РЦОИ">
                                <span class="glyphicon glyphicon-download-alt"></span>
                            </a>&nbsp;{{ exam.date }}
                        </td>
                        <td data-title="Код ППЭ" >
                            <strong>
                                <a{% if todays_date > exam.date.date|date:"Y-m-d" %} class="text-muted"{% endif %}
                                        href="{{ exam.place.get_absolute_url }}">{{ exam.place.code }}
                                </a>
                            </strong>
                        </td>
                        <td data-title="Наим. ППЭ">
                            <a{% if todays_date > exam.date.date|date:"Y-m-d" %} class="text-muted"{% endif %}
                                    href="{{ exam.place.get_absolute_url }}">{{ exam.place.name }}
                            </a>
                        </td>
                        <td data-title="Адрес ППЭ">
                            <a{% if todays_date > exam.date.date|date:"Y-m-d" %} class="text-muted"{% endif %}
                                    href="https://yandex.ru/maps/?text={{ exam.place.addr|urlencode }}"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    title="Открыть карту">
                                <span class="glyphicon glyphicon-map-marker"></span> {{ exam.place.addr }}
                            </a>
                        </td>
                        <td data-title="Должность">{{ exam.position }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-1"></div>
    </div>
{% endblock %}

gia-api/apps/templates/rcoi/exam.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% load tz %}

{% block description %}{% block title %}Распределение организаторов ЕГЭ и ОГЭ в пункты проведения экзаменов{% endblock %}{% endblock %}

{% if table.page and table.paginator.num_pages > 1 %}
    {% block meta %}
        {% if table.page.has_previous and table_sort %}
            <link rel="canonical" href="{{ link_rel }}?page={{ table.page.number }}"/>
            <link rel="prev" href="{{ link_rel }}?page={{ table.page.previous_page_number }}&sort={{ table_sort }}"/>
        {% elif table.page.has_previous %}
            <link rel="canonical" href="{{ link_rel }}?page={{ table.page.number }}"/>
            <link rel="prev" href="{{ link_rel }}?page={{ table.page.previous_page_number }}"/>
        {% else %}
            {{ block.super }}
        {% endif %}
        {% if table.page.has_next and table_sort %}
            <link rel="next" href="{{ link_rel }}?page={{ table.page.next_page_number }}&sort={{ table_sort }}"/>
        {% elif table.page.has_next %}
            <link rel="next" href="{{ link_rel }}?page={{ table.page.next_page_number }}"/>
        {% endif %}
    {% endblock meta %}
{% endif %}

{% block page_header %}
    <h1>Список организаторов ЕГЭ и ОГЭ</h1>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-3 col-sm-3"></div>
        <div class="col-md-6 col-sm-6">
            {% if updated %}{% localtime off %}
            <div class="text-center bottom-buffer">Обновлено {{ updated|date:"d.m.Y, H:i" }}</div>
            {% endlocaltime %}{% endif %}
            {% crispy filter.form filter.form.helper %}
        </div>
        <div class="col-md-3 col-sm-3"></div>
    </div>
    <div class="row" id="row-main">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">{% render_table table 'table.html' %}</div>
        <div class="col-lg-1"></div>
    </div>
{% endblock %}

gia-api/apps/templates/rcoi/level_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <p><a class="btn btn-default" href="{% url 'rcoi:level_list' %}">ExamLevel Listing</a></p>
    <table class="table">
        <tr>
            <td>level</td>
            <td>{{ object.level }}</td>
        </tr>
    </table>
{% endblock %}

gia-api/apps/templates/rcoi/nav.html
{% load navactive %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Показать меню</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'rcoi:home' %}">ГИА {% now "Y" %} в Москве</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'rcoi:exam' %}">
                    <a href="{% url 'rcoi:exam' %}">Экзамены</a>
                </li>
                <li class="{% navactive request 'rcoi:employee' %}">
                    <a href="{% url 'rcoi:employee' %}">Сотрудники</a>
                </li>
                <li class="{% navactive request 'rcoi:organisation' %}">
                    <a href="{% url 'rcoi:organisation' %}">Организации</a>
                </li>
                <li class="{% navactive request 'rcoi:place' %}">
                    <a href="{% url 'rcoi:place' %}">ППЭ</a>
                </li>
                <li>
                    <a href="https://gia.devmem.ru/about" target="_blank">О сайте</a>
                </li>
                <li>
                    <a href="{% url 'apiv1:schema-swagger-ui' %}" target="_blank">API</a>
                </li>
                <li>
                    <a href="https://github.com/spirkaa/gia-api" target="_blank">GitHub</a>
                </li>
            </ul>
            {% if sources %}
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                        aria-haspopup="true"
                        aria-expanded="false">Источники <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for source in sources %}
                        <li><a href="{{ source.url }}"
                                target="_blank"
                                rel="noopener noreferrer">{{ source.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            {% endif %}
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

gia-api/apps/templates/rcoi/organisation.html
{% extends 'rcoi/exam.html' %}
{% block description %}Список образовательных организаций, сотрудники которых задействованных в работе ППЭ: организаторы аудитории, технические специалисты, руководители ППЭ, члены ГЭК на ЕГЭ и ОГЭ{% endblock %}
{% block title %}Организации сотрудников, участвующих в ГИА | Организаторы, технические специалисты, руководители ППЭ, члены ГЭК на ЕГЭ и ОГЭ{% endblock %}
{% block page_header %}
    <h1>Организации работников, распределённых на ППЭ</h1>
{% endblock %}

gia-api/apps/templates/rcoi/organisation_detail.html
{% extends "base.html" %}
{% load rupluralize %}
{% block description %}Сотрудники и учителя {{ object.name }}, заявлянные на ЕГЭ и ОГЭ как работники пунктов проведения экзаменов: организаторы аудитории, технические специалисты, руководители ППЭ, члены ГЭК{% endblock %}
{% block title %}{{ object.name }} | Распределение сотрудников на ППЭ{% endblock %}
{% block page_header %}
    <h1>{{ object.name }}<br/>
        <small>{{ employees.count }} {{ employees.count|rupluralize:"работник,работника,работников" }} ППЭ от организации</small>
    </h1>
{% endblock %}
{% block content %}
    <div class="row" id="row-main">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="no-more-tables">
                <table class="table table-condensed table-hover table-sticky-header">
                    <thead>
                    <tr>
                        <th>ФИО</th>
                        <th>Кол-во</th>
                        {% for date in dates %}
                        <th>{{ date }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for employee in employees %}
                        <tr>
                            <th scope="row" data-title="ФИО"><a href="{{ employee.get_absolute_url }}">{{ employee.name }}</a></th>
                            <td data-title="Кол-во">{{ employee.num_exams }}</td>
                            {% for date in dates %}
                            <td data-title="{{ date }}">
                                {% for exam in employee.exams.all %}
                                    {% if exam.date.id == date.id %}
                                        <a href="{{ exam.place.get_absolute_url }}?date={{ exam.date.id }}">
                                            <strong>{{ exam.place.code }}</strong>
                                        </a>
                                        <span class="text-muted glyphicon glyphicon-info-sign"
                                            data-toggle="tooltip"
                                            data-placement="top"
                                            title="{{ exam.place.name }}, {{ exam.position.name }} ({{ exam.level.level }})">
                                        </span>
                                    {% endif %}
                                {% endfor %}
                            &nbsp;</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
{% endblock %}

gia-api/apps/templates/rcoi/place_detail.html
{% extends "rcoi/exam.html" %}
{% block description %}Организаторы ППЭ {{ place.code }} {{ place.name }} задействованность{% endblock %}
{% block title %}ППЭ {{ place.code }} {{ place.name }} задействованность руководитель организаторы{% endblock %}
{% block page_header %}
    <h1>
        <small>
            <a
                href="https://yandex.ru/maps/?text={{ place.addr|urlencode }}"
                target="_blank"
                rel="noopener noreferrer"
                title="Открыть карту">
                <span class="glyphicon glyphicon-map-marker"></span> {{ place.addr }}
            </a>
        </small>
        <br/>
        ППЭ {{ place.code }} ({{ place.name }})
    </h1>
{% endblock %}

gia-api/apps/templates/rcoi/position_detail.html
{% extends "base.html" %}
{% block content %}
    <p><a class="btn btn-default" href="{% url 'rcoi:position_list' %}">Position Listing</a></p>
    <table class="table">
        <tr>
            <td>name</td>
            <td>{{ object.name }}</td>
        </tr>
    </table>
{% endblock %}

gia-api/apps/templates/rcoi/position_list.html
{% extends "base.html" %}
{% block content %}
    <p><a class="btn btn-default" href="{% url 'rcoi:position_list' %}">Position Listing</a></p>
    <table class="table">
        <tr>
            <td>ID</td>
            <td>Link</td>
            <td>name</td>
        </tr>
        {% for object in object_list %}
            <tr>
                <td>{{ object.id }}</td>
                <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
                <td>{{ object.name }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}